services:
  api:
    build: . 
    container_name: fastify-api
    restart: always
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-db

volumes:
  pgdata: